plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/opt/build/repo/artifacts/mockup-sandbox/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm --filter @workspace/mockup-sandbox... run build"

[build.environment]
PORT = "3000"
BASE_PATH = "/"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]